// Code generated by mockery v2.53.4. DO NOT EDIT.

// Regenerate this file using `make store-mocks`.

package mocks

import (
	model "github.com/mattermost/mattermost/server/public/model"
	mock "github.com/stretchr/testify/mock"
)

// EngageChatStore is an autogenerated mock type for the EngageChatStore type
type EngageChatStore struct {
	mock.Mock
}

// HasChannelMemberWithRoles provides a mock function with given fields: channelID, options
func (_m *EngageChatStore) HasChannelMemberWithRoles(channelID string, options *model.EngageChatRoleSearchOptions) (bool, error) {
	ret := _m.Called(channelID, options)

	if len(ret) == 0 {
		panic("no return value specified for HasChannelMemberWithRoles")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string, *model.EngageChatRoleSearchOptions) (bool, error)); ok {
		return rf(channelID, options)
	}
	if rf, ok := ret.Get(0).(func(string, *model.EngageChatRoleSearchOptions) bool); ok {
		r0 = rf(channelID, options)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string, *model.EngageChatRoleSearchOptions) error); ok {
		r1 = rf(channelID, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewEngageChatStore creates a new instance of EngageChatStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEngageChatStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *EngageChatStore {
	mock := &EngageChatStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
